# Generated by Django 5.2.2 on 2025-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('assigned_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
