# Generated by Django 5.2.2 on 2025-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquecode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
