# Generated by Django 5.2.2 on 2025-06-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='courier_name',
        ),
    ]
