# Generated by Django 5.2.2 on 2025-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_courier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
