# Generated by Django 5.2.2 on 2025-07-04 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_courier_name_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 4, 10, 18, 45, 889371, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
