# Generated by Django 5.2.2 on 2025-06-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
