# Generated by Django 5.2.2 on 2025-06-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_product_available_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('T-shirts', 'T-shirts'), ('Notebooks', 'Notebooks'), ('Water Bottles', 'Water Bottles')], max_length=100),
        ),
    ]
