# Generated by Django 5.2.2 on 2025-06-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='T-shirts', max_length=100),
            preserve_default=False,
        ),
    ]
