# Generated by Django 5.2.2 on 2025-06-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('T-shirts', 'T-shirts'), ('Notebooks', 'Notebooks'), ('Bottles', 'Bottles')], max_length=100),
        ),
    ]
