# Generated by Django 5.2.2 on 2025-06-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
